server:
  port: 80
spring:
  profiles:
    active: dev


  #热部署配置
  devtools:
    restart:
      enabled: true

#配置mybatis扫描mapper.xml  不能Springboot代替扫描，需mybatis自己扫描
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#oss云存储配置
oss:
  easyword:
    type: 1
    aliyunDomain: https://etgame-easy-word.oss-cn-beijing.aliyuncs.com/
    #picture存储路径,不指定默认为空
    aliyunPicPrefix: easy_word_pic
    #video存储路径
    aliyunVideoPrefix: easy_word_video
    #audio存储路径
    aliyunAudioPrefix: easy_word_audio
    #db存储路径
    aliyunDbPrefix: easy_word_db/
    #本地db存储路径
    aliyunDbLocation: /YICI/source/dbFile/base.db
    aliyunEndPoint: https://oss-cn-beijing.aliyuncs.com
    aliyunAccessKeyId: LTAIu1A4PtYpoX5S
    aliyunAccessKeySecret: s38vKBhxbrQmpz9d1WwsiFSmrA6XXS
    aliyunBucketName: etgame-easy-word


#上传文件大小配置 #单位MB
file:
  picSize: 20
  vedioSize: 500
  audioSize: 1

#音频内容处理ffmpeg客户端路径
ffmpeg:
  windows:
    ffprobePath: D:\person\commonTools\ffmpeg\bin\ffprobe.exe
    ffmpegPath: D:\person\commonTools\ffmpeg\bin\ffmpeg.exe
  linux:
    ffprobePath: /usr/bin/ffprobe
    ffmpegPath: /usr/bin/ffmpeg

data:
  mongodb:
    host: 192.168.68.129
    port: 27017
    database: mall

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000