server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid.:
      driver-class-name: com.mysql.jdbc.Driver
     # url: jdbc:mysql://192.168.241.3:3306/nontax_clear?useUnicode=true&characterEncoding=utf8&useSSL=false
      url: jdbc:mysql://127.0.0.1:3306/tmall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，’wall’用于防火墙
      filters: stat,wall,log4j,config
      #最大连接数
      max-active: 100
      #初始化大小
      initial-size: 1
      #获取连接等待超时时间
      max-wait: 60000
      min-idle: 1
      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
#配置mybatis扫描mapper.xml  不能Springboot代替扫描，需mybatis自己扫描
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
mybatis-plus:
    mapper-locations: classpath:mapping/*.xml
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#oss云存储配置
oss:
  easyword:
    type: 1
    aliyunDomain: https://etgame-easy-word.oss-cn-beijing.aliyuncs.com/
    #picture存储路径,不指定默认为空
    aliyunPicPrefix: easy_word_pic
    #video存储路径
    aliyunVideoPrefix: easy_word_video
    #audio存储路径
    aliyunAudioPrefix: easy_word_audio
    #db存储路径
    aliyunDbPrefix: easy_word_db/
    #本地db存储路径
    aliyunDbLocation: /YICI/source/dbFile/base.db
    aliyunEndPoint: https://oss-cn-beijing.aliyuncs.com
    aliyunAccessKeyId: LTAIu1A4PtYpoX5S
    aliyunAccessKeySecret: s38vKBhxbrQmpz9d1WwsiFSmrA6XXS
    aliyunBucketName: etgame-easy-word


#上传文件大小配置 #单位MB
file:
  picSize: 20
  vedioSize: 500
  audioSize: 1

#音频内容处理ffmpeg客户端路径
ffmpeg:
  windows:
    ffprobePath: D:\person\commonTools\ffmpeg\bin\ffprobe.exe
    ffmpegPath: D:\person\commonTools\ffmpeg\bin\ffmpeg.exe
  linux:
    ffprobePath: /usr/bin/ffprobe
    ffmpegPath: /usr/bin/ffmpeg
